#!/bin/bash

MAX_SIZE=100000

for file in dist/*
do
    SIZE=$(du -k "$file" | cut -f1)
    if [ $SIZE -ge $MAX_SIZE ]
    then
        echo "Error: $file is larger than the github limit of 100 MB"
        exit 1
    fi
done

git add dist --ignore-removal
git commit -m "Updated dist files"
