#!/bin/bash

PYINSTALLER_PATH=../pyinstaller/ # Set this appropriatly

# Only use this flag if you are building a windows exe on linux or a mac
# For this you need wine with python 3 installed with all needed libs
# I (Lucas) should really only ever be the one that needs this
if [[ $@ == *--wine-build* ]]
then
    echo "Building with python on wine..."
    PYINSTALLER="wine python ../$PYINSTALLER_PATH/pyinstaller.py"
else
    PYINSTALLER="python ../$PYINSTALLER_PATH/pyinstaller.py"
fi

PYINSTALLER_FLAGS="-F --distpath ../dist --workpath ../build"

cd src
$PYINSTALLER $PYINSTALLER_FLAGS flight_test_gui.py
$PYINSTALLER $PYINSTALLER_FLAGS static_test_gui.py
