#!/bin/bash

# Set this appropriately to the path to the pyinstaller script
PYINSTALLER_PATH=../pyinstaller/pyinstaller.py

PYINSTALLER_FLAGS="-F --windowed"

# Only use this flag if you are building a windows exe on linux or a mac
# For this you need wine with python 3 installed with all needed libs
# I (Lucas) should really only ever be the one that needs this
if [[ $@ == *--wine-build* ]]
then
    echo "Building with python on wine..."
    PYINSTALLER="wine python $PYINSTALLER_PATH"
else
    PYINSTALLER="python3 $PYINSTALLER_PATH"
fi

# Copy sources to another working folder, to avoid dumping .spec files in src
mkdir -p tmp
cp src/*.py tmp

# Build all targets in parallel
$PYINSTALLER $PYINSTALLER_FLAGS tmp/flight_test_gui.py &
$PYINSTALLER $PYINSTALLER_FLAGS tmp/static_test_gui.py &
wait

rm -r tmp
